name: app_faca_festa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
    
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geocoding: ^3.0.0
  uuid: ^4.0.0
  shimmer: ^3.0.0
  flutter_slidable: ^3.1.2
  fl_chart: ^0.71.0
  carousel_slider: ^5.1.1
  flutter_animate: ^4.5.2
  get: ^4.7.2
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter  
  intl: ^0.19.0
  percent_indicator: ^4.2.5
  google_fonts: ^6.3.0
  google_maps_flutter: ^2.11.0
  font_awesome_flutter: ^10.9.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  flutter_easyloading: ^3.0.5
  get_storage: ^2.1.1
  provider: ^6.1.5+1
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  url_launcher: ^6.3.2
  collection: ^1.19.0
  interactive_country_map: ^0.0.6
  mask_text_input_formatter: ^2.9.0
  animate_do: ^4.2.0
  image_picker: ^1.2.0
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
  flutter_tts: ^4.2.3
  geolocator: ^13.0.4
  email_validator: ^3.0.0
  br_validators: ^2.0.4
  qr_flutter: ^4.1.0
  flutter_staggered_grid_view: ^0.7.0
  currency_text_input_formatter: ^2.3.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo-faca-festa.png"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/logo/logo-faca-festa.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

  windows:
    generate: true
    image_path: "assets/logo/logo-faca-festa.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/logo/logo-faca-festa.png"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/logo/
    - assets/images/
    - assets/lottie/
    - assets/animations/
