export const ANALISE_CALCULADORA_IA_SCHEMA_VERSION = "1.1.0";

export const analiseCalculadoraIASchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "titulo",
    "resumo",
    "indice_economia",
    "indice_risco_faltar_itens",
    "indice_conforto",
    "custo_total_estimado",
    "orcamento_disponivel",
    "diferenca_orcamento",
    "data_analise",
    "sugestoes",
    "diagnostico_financeiro",
    "diagnostico_consumo",
    "recomendacao_final",
    "pontos_de_atencao",
    "proximas_acoes",
    "fonte",
    "versao_schema",
  ],
  properties: {
    titulo: { type: "string" },
    resumo: { type: "string" },
    indice_economia: { type: "number", minimum: 0, maximum: 100 },
    indice_risco_faltar_itens: { type: "number", minimum: 0, maximum: 100 },
    indice_conforto: { type: "number", minimum: 0, maximum: 100 },
    custo_total_estimado: { type: "number", minimum: 0 },
    orcamento_disponivel: { type: ["number", "null"], minimum: 0 },
    diferenca_orcamento: { type: "number" },
    data_analise: { type: "string" },
    sugestoes: {
      type: "array",
      minItems: 0,
      maxItems: 8,
      items: {
        type: "object",
        additionalProperties: false,
        required: [
          "id",
          "titulo",
          "descricao",
          "tipo",
          "prioridade",
          "item_relacionado",
          "impacto_estimado",
        ],
        properties: {
          id: { type: "string" },
          titulo: { type: "string" },
          descricao: { type: "string" },
          tipo: {
            type: "string",
            enum: ["economia", "alerta", "melhoria", "excesso", "falta", "planejamento"],
          },
          prioridade: { type: "string", enum: ["baixa", "media", "alta"] },
          item_relacionado: { type: ["string", "null"] },
          impacto_estimado: { type: "number" },
        },
      },
    },
    diagnostico_financeiro: { type: "string" },
    diagnostico_consumo: { type: "string" },
    recomendacao_final: { type: "string" },
    pontos_de_atencao: {
      type: "array",
      minItems: 0,
      maxItems: 8,
      items: { type: "string" },
    },
    proximas_acoes: {
      type: "array",
      minItems: 0,
      maxItems: 8,
      items: { type: "string" },
    },
    fonte: { type: "string", enum: ["ia_generativa", "fallback_local"] },
    versao_schema: { type: "string" },
  },
} as const;
