// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl3iHPrTS4ELhh6wlhWqnS255sjMjijOo',
    appId: '1:300274184803:web:5c83fc48b8976ff035fe56',
    messagingSenderId: '300274184803',
    projectId: 'faca-a-festa',
    authDomain: 'faca-a-festa.firebaseapp.com',
    storageBucket: 'faca-a-festa.firebasestorage.app',
    measurementId: 'G-R35KCWYYN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbusofhs3GIRJH_zIQD_n0yYN1FrLoHbU',
    appId: '1:300274184803:android:719c568e438fd20c35fe56',
    messagingSenderId: '300274184803',
    projectId: 'faca-a-festa',
    storageBucket: 'faca-a-festa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_Y4nKFFKgnqcTi3GoIRLQlf6a5-QjcU',
    appId: '1:300274184803:ios:5b57a4f0c7dd5c9435fe56',
    messagingSenderId: '300274184803',
    projectId: 'faca-a-festa',
    storageBucket: 'faca-a-festa.firebasestorage.app',
    iosBundleId: 'com.example.appFacaFesta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA_Y4nKFFKgnqcTi3GoIRLQlf6a5-QjcU',
    appId: '1:300274184803:ios:5b57a4f0c7dd5c9435fe56',
    messagingSenderId: '300274184803',
    projectId: 'faca-a-festa',
    storageBucket: 'faca-a-festa.firebasestorage.app',
    iosBundleId: 'com.example.appFacaFesta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl3iHPrTS4ELhh6wlhWqnS255sjMjijOo',
    appId: '1:300274184803:web:8c2990c85ca88ff835fe56',
    messagingSenderId: '300274184803',
    projectId: 'faca-a-festa',
    authDomain: 'faca-a-festa.firebaseapp.com',
    storageBucket: 'faca-a-festa.firebasestorage.app',
    measurementId: 'G-TY1V8W65MY',
  );
}
