export const AREAS_AUDITORIA = [
  "ACESSO",
  "USUARIO",
  "FORNECEDOR",
  "SERVICO",
  "CATALOGO",
  "EVENTO",
  "ORCAMENTO",
  "COTACAO",
  "SISTEMA",
] as const;

export const NIVEIS_AUDITORIA = ["CRITICAL", "ERROR", "WARN", "INFO"] as const;

export type AreaAuditoria = (typeof AREAS_AUDITORIA)[number];
export type NivelAuditoria = (typeof NIVEIS_AUDITORIA)[number];

export type DefinicaoAcaoAuditoria = {
  area: AreaAuditoria;
  nivel: NivelAuditoria;
  visivelFornecedor: boolean;
  somenteAdmin: boolean;
};

export const CATALOGO_ACOES_AUDITORIA: Record<string, DefinicaoAcaoAuditoria> = {
  LOGIN_REALIZADO: {
    area: "ACESSO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  LOGOUT_REALIZADO: {
    area: "ACESSO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  LOGIN_FALHOU: {
    area: "ACESSO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  SENHA_REDEFINICAO_SOLICITADA: {
    area: "ACESSO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  SENHA_REDEFINIDA: {
    area: "ACESSO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  MFA_EMAIL_CODIGO_SOLICITADO: {
    area: "ACESSO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  MFA_EMAIL_CONFIRMADO: {
    area: "ACESSO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  MFA_EMAIL_VERIFICADO: {
    area: "ACESSO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  MFA_TOTP_INICIADO: {
    area: "ACESSO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  MFA_TOTP_CONFIRMADO: {
    area: "ACESSO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  MFA_TOTP_VERIFICADO: {
    area: "ACESSO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  USUARIO_CRIADO: {
    area: "USUARIO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  USUARIO_TIPO_ALTERADO: {
    area: "USUARIO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  USUARIO_STATUS_ALTERADO: {
    area: "USUARIO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  USUARIO_ATUALIZADO: {
    area: "USUARIO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  USUARIO_EXCLUIDO: {
    area: "USUARIO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  USUARIO_ENDERECO_CRIADO: {
    area: "USUARIO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  USUARIO_ENDERECO_ATUALIZADO: {
    area: "USUARIO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  USUARIO_ENDERECO_EXCLUIDO: {
    area: "USUARIO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  FORNECEDOR_CRIADO: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  FORNECEDOR_ATUALIZADO: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  FORNECEDOR_EXCLUIDO: {
    area: "FORNECEDOR",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: true,
  },
  FORNECEDOR_APROVADO: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: true,
  },
  FORNECEDOR_REPROVADO: {
    area: "FORNECEDOR",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: true,
  },
  FORNECEDOR_ATIVADO: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: true,
  },
  FORNECEDOR_DESATIVADO: {
    area: "FORNECEDOR",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: true,
  },
  FORNECEDOR_EDITADO: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  TERRITORIO_CRIADO: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  TERRITORIO_REGISTRADO: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  TERRITORIO_ATUALIZADO: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  TERRITORIO_EXCLUIDO: {
    area: "FORNECEDOR",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  SERVICO_CATALOGO_SALVO: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  SERVICO_CATALOGO_CRIADO: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  SERVICO_CATALOGO_ATUALIZADO: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  SERVICO_CATALOGO_EXCLUIDO: {
    area: "CATALOGO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  CATEGORIA_SALVA: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  CATEGORIA_CRIADA: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  CATEGORIA_ATUALIZADA: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  CATEGORIA_EXCLUIDA: {
    area: "CATALOGO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  SUBCATEGORIA_CRIADA: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  SUBCATEGORIA_ATUALIZADA: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  SUBCATEGORIA_EXCLUIDA: {
    area: "CATALOGO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  CIDADE_CRIADA: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  CIDADE_ATUALIZADA: {
    area: "CATALOGO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  CIDADE_EXCLUIDA: {
    area: "CATALOGO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  SERVICO_FORNECEDOR_SALVO: {
    area: "SERVICO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  SERVICO_FORNECEDOR_CRIADO: {
    area: "SERVICO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  SERVICO_FORNECEDOR_ATUALIZADO: {
    area: "SERVICO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  SERVICO_FORNECEDOR_EXCLUIDO: {
    area: "SERVICO",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  SERVICO_AVALIACAO_CRIADA: {
    area: "SERVICO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  SERVICO_AVALIACAO_ATUALIZADA: {
    area: "SERVICO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  SERVICO_AVALIACAO_EXCLUIDA: {
    area: "SERVICO",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  EVENTO_APROVADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  EVENTO_CRIADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  EVENTO_ATUALIZADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  EVENTO_EXCLUIDO: {
    area: "EVENTO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  PRESENTE_CRIADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  PRESENTE_ATUALIZADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  PRESENTE_EXCLUIDO: {
    area: "EVENTO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  PRESENTE_CONTRIBUICAO_CRIADA: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  PRESENTE_CONTRIBUICAO_ATUALIZADA: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  PRESENTE_CONTRIBUICAO_EXCLUIDA: {
    area: "EVENTO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  EVENTO_TAREFA_CRIADA: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  EVENTO_TAREFA_ATUALIZADA: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  EVENTO_TAREFA_EXCLUIDA: {
    area: "EVENTO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  EVENTO_ORCAMENTO_CRIADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  EVENTO_ORCAMENTO_ATUALIZADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  EVENTO_ORCAMENTO_EXCLUIDO: {
    area: "EVENTO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  CARDAPIO_ITEM_CRIADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  CARDAPIO_ITEM_ATUALIZADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  CARDAPIO_ITEM_EXCLUIDO: {
    area: "EVENTO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  CALCULADORA_ITEM_CRIADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  CALCULADORA_ITEM_ATUALIZADO: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  CALCULADORA_ITEM_EXCLUIDO: {
    area: "EVENTO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  CALCULADORA_ANALISE_IA_CRIADA: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  CALCULADORA_ANALISE_IA_ATUALIZADA: {
    area: "EVENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  CALCULADORA_ANALISE_IA_EXCLUIDA: {
    area: "EVENTO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  ORCAMENTO_RESPONDIDO: {
    area: "ORCAMENTO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  ORCAMENTO_FECHADO: {
    area: "ORCAMENTO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  ORCAMENTO_CANCELADO: {
    area: "ORCAMENTO",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  ORCAMENTO_CRIADO: {
    area: "ORCAMENTO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  ORCAMENTO_ATUALIZADO: {
    area: "ORCAMENTO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  ORCAMENTO_EXCLUIDO: {
    area: "ORCAMENTO",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  ORCAMENTO_GASTO_CRIADO: {
    area: "ORCAMENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  ORCAMENTO_GASTO_ATUALIZADO: {
    area: "ORCAMENTO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  ORCAMENTO_GASTO_EXCLUIDO: {
    area: "ORCAMENTO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  COTACAO_CRIADA: {
    area: "COTACAO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  COTACAO_ATUALIZADA: {
    area: "COTACAO",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  COTACAO_EXCLUIDA: {
    area: "COTACAO",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: true,
  },
  COTACAO_RESPONDIDA: {
    area: "COTACAO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  COTACAO_FECHADA: {
    area: "COTACAO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  COTACAO_CANCELADA: {
    area: "COTACAO",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  COTACAO_FORNECEDOR_CRIADA: {
    area: "COTACAO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  COTACAO_FORNECEDOR_ATUALIZADA: {
    area: "COTACAO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  COTACAO_FORNECEDOR_EXCLUIDA: {
    area: "COTACAO",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  COTACAO_SERVICO_CRIADO: {
    area: "COTACAO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  COTACAO_SERVICO_ATUALIZADO: {
    area: "COTACAO",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  COTACAO_SERVICO_EXCLUIDO: {
    area: "COTACAO",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  FORNECEDOR_AVALIACAO_CRIADA: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  FORNECEDOR_AVALIACAO_ATUALIZADA: {
    area: "FORNECEDOR",
    nivel: "INFO",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  FORNECEDOR_AVALIACAO_EXCLUIDA: {
    area: "FORNECEDOR",
    nivel: "WARN",
    visivelFornecedor: true,
    somenteAdmin: false,
  },
  POST_COMENTARIO_CRIADO: {
    area: "SISTEMA",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  POST_COMENTARIO_ATUALIZADO: {
    area: "SISTEMA",
    nivel: "INFO",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
  POST_COMENTARIO_EXCLUIDO: {
    area: "SISTEMA",
    nivel: "WARN",
    visivelFornecedor: false,
    somenteAdmin: false,
  },
};

export const ACAO_PADRAO: DefinicaoAcaoAuditoria = {
  area: "SISTEMA",
  nivel: "INFO",
  visivelFornecedor: false,
  somenteAdmin: false,
};

export function definirAcao(acao: string): DefinicaoAcaoAuditoria {
  return CATALOGO_ACOES_AUDITORIA[acao] ?? ACAO_PADRAO;
}
